name: 'CI'
on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_IP_IHOR}}
          username: ${{secrets.SERVER_USERNAME_IHOR}}
          password: ${{secrets.SERVER_PASSWORD_IHOR}}
          port: ${{secrets.PORT}}
          script: cd ${{secrets.PROJECT_PATH_IHOR }} && bash deploy.sh
        


